### ISSUE TITLE
Unable to Signin

### ISSUE THREAD

**Issue by marshallellis** [gsuitedevs/android-samples#115]
## Expected Behavior
Get a signin

## Actual Behavior
Unable to signin message.
Along with Exception
com.google.android.gms.common.api.ApiException: 10: 
        at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(Unknown Source:4)
        at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(Unknown Source:8)
        at com.dcc.doogle.doogledrive.googlelogin_rcv_intent(doogledrive.java:109)
        at com.dcc.std_client.DCCClientActivity.onActivityResult(DCCClientActivity.java:456)
        at android.app.Activity.dispatchActivityResult(Activity.java:7556)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374

## Steps to Reproduce the Problem

1.Simply execute a sign-in.
I believe I may be missing a json key or something like??? BUT not sure where to implement this json file which the API Console generated??? AM I missing some instructions???

**Comment by erickoledadevrel** [comment]
Yes, you need to configure a client with a SHA-1 hash. More information here:

https://developers.google.com/identity/sign-in/android/start
